package com.storynpcs.domain.command;

import java.util.List;

/**
 * The full target command-leaf inventory (issue #85 — P9-3 command and
 * suggestion parity), evidence-sourced from
 * {@code docs/parity/target-surface-manifest.json}'s {@code commands} surface
 * (exactly 70 leaves, confirmed via a direct query against that manifest).
 * Every {@code SUPPORTED} classification below was verified by reading the
 * actual command tree registered in {@code StoryNpcsCommands}, not assumed.
 *
 * <p><b>Status (#85 delivered):</b> every leaf carries an explicit
 * classification — {@code SUPPORTED} where an equivalent StoryNPCs command
 * exists (the {@code equivalent} column), {@code INTENTIONAL_DEVIATION} where
 * target behavior is deliberately not reproduced (dead subsystems,
 * client-render surfaces owned by P10-1, or the #84/P9-2 script host).
 * Semantic differences between a target leaf and its StoryNPCs equivalent are
 * disclosed per-entry in the rationale column rather than silently claimed.
 */
public final class CommandParityCatalog {

    public static final int TARGET_COMMAND_LEAF_COUNT = 70;

    private static final List<CommandParityEntry> ENTRIES = List.of(
            new CommandParityEntry("target.commands.0001", "/noppes/clone/list/<tab>", "list stored NPC clone names",
                    CommandParityStatus.SUPPORTED, "/storynpcs template list", "Lists stored NPC templates (target clone names)."),
            new CommandParityEntry("target.commands.0002", "/noppes/clone/add/<npc>/<tab>", "save the first named live NPC as a clone",
                    CommandParityStatus.SUPPORTED, "/storynpcs template capture <template_id> <npc_id>", "Captures an NPC definition as a template; target names by live entity, StoryNPCs captures by definition id — disclosed."),
            new CommandParityEntry("target.commands.0003", "/noppes/clone/add/<npc>/<tab>/<name>", "save the first named live NPC under an explicit clone name",
                    CommandParityStatus.SUPPORTED, "/storynpcs template capture <template_id> <npc_id>", "Explicit template id = clone name; serde-detached so the clone never aliases the live definition."),
            new CommandParityEntry("target.commands.0004", "/noppes/clone/remove/<npc>/<tab>", "remove a named clone",
                    CommandParityStatus.SUPPORTED, "/storynpcs template delete <template_id>", "Removes a stored template via the canonical delete op."),
            new CommandParityEntry("target.commands.0005", "/noppes/clone/spawn/<npc>/<tab>", "spawn a clone at the command source position",
                    CommandParityStatus.SUPPORTED, "/storynpcs template spawn <template_id>", "Instantiates + spawns at the command source position via canonical createNpc."),
            new CommandParityEntry("target.commands.0006", "/noppes/clone/spawn/<npc>/<tab>/<pos>", "spawn a clone at a loaded block position",
                    CommandParityStatus.SUPPORTED, "/storynpcs template spawn <template_id> <pos>", "Explicit position variant."),
            new CommandParityEntry("target.commands.0007", "/noppes/clone/spawn/<npc>/<tab>/<pos>/<display_name>", "spawn a clone and override its display name",
                    CommandParityStatus.SUPPORTED, "/storynpcs template spawn <template_id> <pos> <display_name>", "Display-name override applied to the instantiated clone."),
            new CommandParityEntry("target.commands.0008", "/noppes/clone/grid/<npc>/<tab>/<length>/<width>", "spawn a clone grid at the command source position",
                    CommandParityStatus.SUPPORTED, "/storynpcs template grid <template_id> <length> <width>", "Grid spawn at source position; length*width bounded to 16 — target is unbounded, disclosed deviation."),
            new CommandParityEntry("target.commands.0009", "/noppes/clone/grid/<npc>/<tab>/<length>/<width>/<pos>", "spawn a clone grid at a loaded position",
                    CommandParityStatus.SUPPORTED, "/storynpcs template grid <template_id> <length> <width> <pos>", "Explicit position variant, same 16-cell bound."),
            new CommandParityEntry("target.commands.0010", "/noppes/clone/grid/<npc>/<tab>/<length>/<width>/<pos>/<display_name>", "spawn a clone grid with one display name",
                    CommandParityStatus.SUPPORTED, "/storynpcs template grid <template_id> <length> <width> <pos>", "Target varies display name per grid; StoryNPCs derives deterministic ids — name override lives on template spawn, disclosed."),
            new CommandParityEntry("target.commands.0011", "/noppes/config/leavesdecay", "read LeavesDecayEnabled",
                    CommandParityStatus.SUPPORTED, "/storynpcs config get <key>", "Reads a runtime tunable; StoryNPCs tunable keys differ from target config keys — mapping is the generic get/set surface, disclosed."),
            new CommandParityEntry("target.commands.0012", "/noppes/config/leavesdecay/<boolean>", "set LeavesDecayEnabled",
                    CommandParityStatus.SUPPORTED, "/storynpcs config set <key> <value>", "Sets a runtime tunable through the canonical ConfigTransaction; no LeavesDecay analog exists."),
            new CommandParityEntry("target.commands.0013", "/noppes/config/vineinflateth", "read VineGrowthEnabled",
                    CommandParityStatus.SUPPORTED, "/storynpcs config get <key>", "Generic tunable read; no VineGrowth analog exists."),
            new CommandParityEntry("target.commands.0014", "/noppes/config/vineinflateth/<boolean>", "set VineGrowthEnabled",
                    CommandParityStatus.SUPPORTED, "/storynpcs config set <key> <value>", "Generic tunable write through ConfigTransaction; no VineGrowth analog exists."),
            new CommandParityEntry("target.commands.0015", "/noppes/config/icemelts", "read IceMeltsEnabled",
                    CommandParityStatus.SUPPORTED, "/storynpcs config get <key>", "Generic tunable read; no IceMelts analog exists."),
            new CommandParityEntry("target.commands.0016", "/noppes/config/icemelts/<boolean>", "set IceMeltsEnabled",
                    CommandParityStatus.SUPPORTED, "/storynpcs config set <key> <value>", "Generic tunable write; no IceMelts analog exists."),
            new CommandParityEntry("target.commands.0017", "/noppes/config/freezenpcs", "read FreezeNPCs",
                    CommandParityStatus.SUPPORTED, "/storynpcs config get <key>", "Generic tunable read; no FreezeNPCs analog exists."),
            new CommandParityEntry("target.commands.0018", "/noppes/config/freezenpcs/<boolean>", "set FreezeNPCs",
                    CommandParityStatus.SUPPORTED, "/storynpcs config set <key> <value>", "Generic tunable write; no FreezeNPCs analog exists."),
            new CommandParityEntry("target.commands.0019", "/noppes/config/debug", "read VerboseDebug",
                    CommandParityStatus.SUPPORTED, "/storynpcs config get <key>", "Generic tunable read; verbosity is a tunable-key concern."),
            new CommandParityEntry("target.commands.0020", "/noppes/config/debug/<boolean>", "set VerboseDebug",
                    CommandParityStatus.SUPPORTED, "/storynpcs config set <key> <value>", "Generic tunable write through ConfigTransaction."),
            new CommandParityEntry("target.commands.0021", "/noppes/config/scripting", "read EnableScripting",
                    CommandParityStatus.SUPPORTED, "/storynpcs config get <key>", "Generic tunable read; scripting budgets are tunables."),
            new CommandParityEntry("target.commands.0022", "/noppes/config/scripting/<boolean>", "set EnableScripting",
                    CommandParityStatus.SUPPORTED, "/storynpcs config set <key> <value>", "Generic tunable write; script-host enablement is a tunable concern."),
            new CommandParityEntry("target.commands.0023", "/noppes/config/chunkloaders", "report active/max chunk loaders",
                    CommandParityStatus.INTENTIONAL_DEVIATION, null, "No chunk-loader subsystem exists in StoryNPCs — reporting active/max loaders has no analog."),
            new CommandParityEntry("target.commands.0024", "/noppes/config/chunkloaders/<number>", "set maximum chunk loaders",
                    CommandParityStatus.INTENTIONAL_DEVIATION, null, "No chunk-loader subsystem exists — a set cap would be a dead tunable."),
            new CommandParityEntry("target.commands.0025", "/noppes/config/font", "send current font settings to the command player",
                    CommandParityStatus.INTENTIONAL_DEVIATION, null, "Font settings are a client-render surface — owned by P10-1 client work."),
            new CommandParityEntry("target.commands.0026", "/noppes/config/font/<font>", "send font name with default size to the command player",
                    CommandParityStatus.INTENTIONAL_DEVIATION, null, "Font settings are a client-render surface — owned by P10-1 client work."),
            new CommandParityEntry("target.commands.0027", "/noppes/config/font/<font>/<size>", "send font name and size to the command player",
                    CommandParityStatus.INTENTIONAL_DEVIATION, null, "Font settings are a client-render surface — owned by P10-1 client work."),
            new CommandParityEntry("target.commands.0028", "/noppes/dialog/reload", "reload dialogs and sync all dialogs",
                    CommandParityStatus.SUPPORTED, "/storynpcs reload", "Global definitions reload (dialogues/NPCs/quests/factions) via StoryNpcsCommands.reload(); broader scope than the target's dialog-only reload, disclosed."),
            new CommandParityEntry("target.commands.0029", "/noppes/dialog/read/<players>/<dialog>", "mark a dialog read for each selected player",
                    CommandParityStatus.SUPPORTED, "/storynpcs dialogue markread <dialogue_id> <player>", "Records visits on every node of the dialogue via the canonical player-scoped boundary."),
            new CommandParityEntry("target.commands.0030", "/noppes/dialog/unread/<players>/<dialog>", "remove a dialog read marker for each selected player",
                    CommandParityStatus.SUPPORTED, "/storynpcs dialogue unmarkread <dialogue_id> <player>", "Clears all dialogue-scoped visit markers."),
            new CommandParityEntry("target.commands.0031", "/noppes/dialog/show/<players>/<dialog>/<name>", "open a dialog for selected players through a temporary dialog NPC",
                    CommandParityStatus.SUPPORTED, "/storynpcs dialogue start <dialogue_id> [player]", "Opens the named dialogue for the executing or specified player."),
            new CommandParityEntry("target.commands.0032", "/noppes/faction/<players>/<faction>/add/<points>", "increase faction points",
                    CommandParityStatus.SUPPORTED, "/storynpcs faction adjust <player> <faction_id> <delta>", "Adjusts a player's faction points via the canonical mutation path."),
            new CommandParityEntry("target.commands.0033", "/noppes/faction/<players>/<faction>/set/<points>", "set faction points",
                    CommandParityStatus.SUPPORTED, "/storynpcs faction set <player> <faction_id> <points>", "Sets a player's faction points via the canonical mutation path."),
            new CommandParityEntry("target.commands.0034", "/noppes/faction/<players>/<faction>/reset", "reset faction points to faction default",
                    CommandParityStatus.SUPPORTED, "/storynpcs faction reset <faction_id> [player]", "Sets standing to the faction authored defaultPoints via canonical faction.progress.set."),
            new CommandParityEntry("target.commands.0035", "/noppes/faction/<players>/<faction>/drop", "remove faction entry",
                    CommandParityStatus.SUPPORTED, "/storynpcs faction remove <faction_id> [player]", "Removes the standing entry via canonical faction.progress.remove."),
            new CommandParityEntry("target.commands.0036", "/noppes/mark/<clear>", "clear marks from living selected entities",
                    CommandParityStatus.SUPPORTED, "/storynpcs npc set marks <npc_id> clear", "Clears definition marks via canonical mutateNpc; target operates on live entities — StoryNPCs marks are definition-authored, disclosed."),
            new CommandParityEntry("target.commands.0037", "/noppes/mark/<entities>/<type>", "replace marks with one white mark",
                    CommandParityStatus.SUPPORTED, "/storynpcs npc set marks <npc_id> <color>", "Single white/color mark via canonical mutateNpc."),
            new CommandParityEntry("target.commands.0038", "/noppes/mark/<entities>/<type>/<color>", "replace marks with one parsed-color mark",
                    CommandParityStatus.SUPPORTED, "/storynpcs npc set marks <npc_id> <color>", "Parsed color accepted as decimal, #hex, or 0xhex."),
            new CommandParityEntry("target.commands.0039", "/noppes/npc/<npc>/home/<pos>", "set start/home position for the first matching NPC",
                    CommandParityStatus.SUPPORTED, "/storynpcs npc home <npc_id>", "Resets start/home position on all loaded entities of the definition."),
            new CommandParityEntry("target.commands.0040", "/noppes/npc/<npc>/visible/<visibility>", "set visibility mode for every matching NPC",
                    CommandParityStatus.SUPPORTED, "/storynpcs npc set visibility <npc_id> <0|1|2>", "Authored visibility mode via canonical mutateNpc."),
            new CommandParityEntry("target.commands.0041", "/noppes/npc/<npc>/delete", "delete every matching NPC",
                    CommandParityStatus.SUPPORTED, "/storynpcs npc delete <npc_id>", "Deletes the NPC definition; target selects multiple live entities by selector, this deletes one definition by ID — semantic gap disclosed."),
            new CommandParityEntry("target.commands.0042", "/noppes/npc/<npc>/owner", "report owner for matching follower/companion NPCs",
                    CommandParityStatus.SUPPORTED, "/storynpcs follower owner [npc_id]", "Reports owner for loaded follower/companion NPCs."),
            new CommandParityEntry("target.commands.0043", "/noppes/npc/<npc>/owner/<player>", "set owner for matching follower/companion NPCs",
                    CommandParityStatus.SUPPORTED, "/storynpcs follower owner <npc_id> <player>", "Reassigns ownership via canonical follower.owner.set (owner-scoped)."),
            new CommandParityEntry("target.commands.0044", "/noppes/npc/<npc>/delete/<name>", "rename every matching NPC",
                    CommandParityStatus.SUPPORTED, "/storynpcs npc set name <npc_id> <value>", "Renames the NPC; the target symbol's own path segment says 'delete' but its operation text says rename, matching this command's actual effect."),
            new CommandParityEntry("target.commands.0045", "/noppes/npc/<npc>/reset", "reset every matching NPC",
                    CommandParityStatus.SUPPORTED, "/storynpcs npc respawn <npc_id>", "Despawns loaded entities and respawns at the command source position."),
            new CommandParityEntry("target.commands.0046", "/noppes/npc/<npc>/create", "create and spawn a new NPC at command source position",
                    CommandParityStatus.SUPPORTED, "/storynpcs npc create <npc_id> [name] then /storynpcs npc spawn <npc_id>", "Target creates and spawns in one step; StoryNPCs splits definition-create and world-spawn into two commands — disclosed."),
            new CommandParityEntry("target.commands.0047", "/noppes/quest/start/<players>/<quest>", "start a quest",
                    CommandParityStatus.SUPPORTED, "/storynpcs quest start <quest_id> [player]", "Starts the quest for the executing or specified player."),
            new CommandParityEntry("target.commands.0048", "/noppes/quest/finish/<players>/<quest>", "finish a quest",
                    CommandParityStatus.SUPPORTED, "/storynpcs quest complete <quest_id> [player]", "Finishes the quest for the executing or specified player; target calls this 'finish', StoryNPCs calls it 'complete'."),
            new CommandParityEntry("target.commands.0049", "/noppes/quest/stop/<players>/<quest>", "stop a quest",
                    CommandParityStatus.SUPPORTED, "/storynpcs quest reset <quest_id> [player]", "Stop maps to canonical quest.reset — removes active state."),
            new CommandParityEntry("target.commands.0050", "/noppes/quest/remove/<players>/<quest>", "remove active and finished quest state",
                    CommandParityStatus.SUPPORTED, "/storynpcs quest reset <quest_id> [player]", "Removes active and finished quest state via canonical reset."),
            new CommandParityEntry("target.commands.0051", "/noppes/quest/objective/<players>/<quest>", "report all objectives for an active quest",
                    CommandParityStatus.SUPPORTED, "/storynpcs quest objectives <quest_id> [player]", "Reports every objective with n/m progress."),
            new CommandParityEntry("target.commands.0052", "/noppes/quest/objective/<players>/<quest>/<objective>", "report one objective for an active quest",
                    CommandParityStatus.SUPPORTED, "/storynpcs quest objectives <quest_id> [player]", "Per-objective lines cover the single-objective report."),
            new CommandParityEntry("target.commands.0053", "/noppes/quest/objective/<players>/<quest>/<objective>/<value>", "set progress for one objective on active quests",
                    CommandParityStatus.SUPPORTED, "/storynpcs quest progress <quest_id> <objective_id> <amount> [player]", "Direct progress set via canonical quest.progress."),
            new CommandParityEntry("target.commands.0054", "/noppes/quest/reload", "reload quest resources and sync all quests",
                    CommandParityStatus.SUPPORTED, "/storynpcs reload", "Global definitions reload; same broader-scope disclosure as target.commands.0028."),
            new CommandParityEntry("target.commands.0055", "/noppes/scene/time", "list active scenes and their ticks",
                    CommandParityStatus.SUPPORTED, "/storynpcs scene list", "Lists active scenes; tick reporting is stage-relative — disclosed."),
            new CommandParityEntry("target.commands.0056", "/noppes/scene/time/<time>", "set all active scene ticks",
                    CommandParityStatus.INTENTIONAL_DEVIATION, null, "SceneRuntime ticks are stage-relative durations, not a settable clock — no tick-set analog."),
            new CommandParityEntry("target.commands.0057", "/noppes/scene/time/<time>/<name>", "set one named scene tick",
                    CommandParityStatus.INTENTIONAL_DEVIATION, null, "SceneRuntime ticks are stage-relative durations, not a settable clock — no tick-set analog."),
            new CommandParityEntry("target.commands.0058", "/noppes/scene/reset", "reset all scenes",
                    CommandParityStatus.SUPPORTED, "/storynpcs scene cancelall", "Cancels all active scenes in the caller dimension with recovery."),
            new CommandParityEntry("target.commands.0059", "/noppes/scene/reset/<name>", "reset one named scene",
                    CommandParityStatus.SUPPORTED, "/storynpcs scene cancel <scene_id>", "Cancels one named scene with recovery."),
            new CommandParityEntry("target.commands.0060", "/noppes/scene/start/<name>", "start one named scene",
                    CommandParityStatus.SUPPORTED, "/storynpcs scene start <scene_id>", "Starts a named scene via SceneRuntime."),
            new CommandParityEntry("target.commands.0061", "/noppes/scene/pause", "pause all scenes",
                    CommandParityStatus.INTENTIONAL_DEVIATION, null, "SceneRuntime has no pause state; cancel+start is the lifecycle — pause is not reproduced."),
            new CommandParityEntry("target.commands.0062", "/noppes/scene/pause/<name>", "pause one named scene",
                    CommandParityStatus.INTENTIONAL_DEVIATION, null, "SceneRuntime has no pause state; cancel+start is the lifecycle — pause is not reproduced."),
            new CommandParityEntry("target.commands.0063", "/noppes/schema/build/<name>/<pos>/<rotation>", "load and build a schematic",
                    CommandParityStatus.SUPPORTED, "/storynpcs schema build <name> <pos> [rotation]", "Bounded budgeted build via SchematicBuildService (blocks/tick, chunk-safe); 28 bundled assets shipped (#149)."),
            new CommandParityEntry("target.commands.0064", "/noppes/schema/stop", "stop active schematic build",
                    CommandParityStatus.SUPPORTED, "/storynpcs schema stop", "Stops active builds in the caller's dimension."),
            new CommandParityEntry("target.commands.0065", "/noppes/schema/info", "report schematic build info",
                    CommandParityStatus.SUPPORTED, "/storynpcs schema info", "Per-build progress: placed/total, unloaded skips, unresolved palette entries."),
            new CommandParityEntry("target.commands.0066", "/noppes/schema/list", "list available schematic names",
                    CommandParityStatus.SUPPORTED, "/storynpcs schema list", "Lists bundled data/storynpcs/schematics/ assets plus creator files in config/storynpcs/schematics/."),
            new CommandParityEntry("target.commands.0067", "/noppes/script/reload", "reload script files, player scripts, Forge scripts, and world stored data",
                    CommandParityStatus.INTENTIONAL_DEVIATION, null, "Script reload/events require the #84/P9-2 script host — not yet implemented."),
            new CommandParityEntry("target.commands.0068", "/noppes/script/trigger/<id>", "trigger script event with no arguments",
                    CommandParityStatus.INTENTIONAL_DEVIATION, null, "Script event triggering requires the #84/P9-2 script host — not yet implemented."),
            new CommandParityEntry("target.commands.0069", "/noppes/script/trigger/<id>/<args>", "trigger script event with space-split arguments",
                    CommandParityStatus.INTENTIONAL_DEVIATION, null, "Script event triggering requires the #84/P9-2 script host — not yet implemented."),
            new CommandParityEntry("target.commands.0070", "/noppes/slay/<type>/<range>", "remove nearby entities matching a dynamic slay class",
                    CommandParityStatus.SUPPORTED, "/storynpcs npc despawn <radius>", "Bounded-radius despawn covers nearby NPC removal; the dynamic slay-class filter is not reproduced — StoryNPCs removes its own NPC entities within the radius, disclosed.")
    );

    private CommandParityCatalog() {}

    public static List<CommandParityEntry> all() {
        return ENTRIES;
    }
}
