package com.storynpcs.domain.job;

/**
 * The target's exact 11 job capabilities (issue #73 — job capability inventory).
 * Per the target manifest (docs/parity/target-surface-manifest.json, generated by
 * P0-1), the concrete job classes are: JobBard, JobBuilder, JobChunkLoader,
 * JobConversation, JobFarmer, JobFollower, JobGuard, JobHealer, JobItemGiver,
 * JobPuppet, JobSpawner (11 total; JobInterface is an interface, not counted).
 *
 * <p>Declaring this vocabulary and the shared {@link JobAssignment} lifecycle is
 * this issue's foundation slice. No per-job tick behavior, scheduler integration,
 * or entity/chunk-creation logic exists yet for any job — see JobAssignment's
 * javadoc for the exact scope boundary.
 */
public enum JobType {
    BARD,
    BUILDER,
    CHUNK_LOADER,
    CONVERSATION,
    FARMER,
    FOLLOWER,
    GUARD,
    HEALER,
    ITEM_GIVER,
    PUPPET,
    SPAWNER
}
