"""Regression guard for issue P9-5 (optional-mod integration contracts).

The target manifest (docs/parity/target-surface-manifest.json, generated by
P0-1) records exactly 7 Pixelmon/Cobblemon integration-helper classes found
in the supplied CustomNPCs JAR. P9-5 requires every such integration helper
to have an issue mapping and to be either implemented or explicitly
documented as an intentional deviation.

StoryNPCs' documented decision (docs/parity/P9-5-CLOSEOUT.md) is deviation:
no Pixelmon/Cobblemon integration is implemented. This test enforces the
structural half of that claim mechanically rather than by one-time manual
grep: it fails if the manifest's known integration-helper set drifts (a
regenerated manifest finding more/fewer/different such classes would need
this closeout revisited), and it fails if any file under src/main ever
references Pixelmon or Cobblemon, which would silently violate "no optional
class load crashes a server without the dependency" and the declared
deviation itself.
"""

import json
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = REPO_ROOT / "docs" / "parity" / "target-surface-manifest.json"

EXPECTED_INTEGRATION_SYMBOLS = {
    "noppes.npcs.api.entity.IPixelmon",
    "noppes.npcs.api.entity.data.IPixelmonPlayerData",
    "noppes.npcs.api.wrapper.PixelmonWrapper",
    "noppes.npcs.client.gui.model.GuiCreationExtra$GuiTypeCobblemon",
    "noppes.npcs.client.gui.model.GuiCreationExtra$GuiTypePixelmon",
    "noppes.npcs.controllers.CobblemonHelper",
    "noppes.npcs.controllers.PixelmonHelper",
}


class P95OptionalIntegrationsTest(unittest.TestCase):
    def test_manifest_integration_helper_set_matches_documented_deviation(self) -> None:
        with open(MANIFEST_PATH, encoding="utf-8") as handle:
            manifest = json.load(handle)
        classes = manifest["surfaces"]["target_classes"]
        found = {
            entry["symbol"]
            for entry in classes
            if "pixelmon" in entry["symbol"].lower() or "cobblemon" in entry["symbol"].lower()
        }
        self.assertEqual(
            found,
            EXPECTED_INTEGRATION_SYMBOLS,
            "The manifest's Pixelmon/Cobblemon integration-helper set changed. "
            "docs/parity/P9-5-CLOSEOUT.md documents a specific, enumerated deviation "
            "for exactly this set — update that closeout doc (and this test) if the "
            "manifest was regenerated and the set is now different.",
        )

    def test_no_source_file_references_pixelmon_or_cobblemon(self) -> None:
        offenders = []
        for path in (REPO_ROOT / "src" / "main").rglob("*"):
            if not path.is_file():
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            lowered = text.lower()
            if "pixelmon" in lowered or "cobblemon" in lowered:
                offenders.append(str(path.relative_to(REPO_ROOT)))
        self.assertEqual(
            offenders,
            [],
            "docs/parity/P9-5-CLOSEOUT.md declares Pixelmon/Cobblemon integration an "
            "intentional deviation — no source file should reference either mod. If "
            "one of these files legitimately needs to, the deviation decision in that "
            "closeout doc must be revisited first, not silently outdated.",
        )


if __name__ == "__main__":
    unittest.main()
